### ISSUE TITLE
ML train

### ISSUE THREAD

**Issue by Elforia** [Mackbit/Tibia_makerunes#1]
Hello, 

Do you have a script to train Magic Level? I would be very very thankful if you post here more scripts that you have made. Maybe some of them should help lots of people, like me, that have no skills to make their own scripts (like your runemaker) 

Thanks in advance.

**Comment by Elforia** [comment]
@Mackbit

**Comment by Mackbit** [comment]
@Elforia 
What desired functionality would a magic level training script have?
I might be able to help you with a customized script.

**Comment by Elforia** [comment]
@Mackbit
Use potions and cast spells. 
And whatever you want to! =P

 I don't know exactly what is possible with these scripts, but you know. When I saw your runemaker I got freaky, because I never thought that something like that was possible. 

Btw, what kind of scripts do you have there? I just what to know how far can I go with that tool. 

Well... Thanks for answer me, bro.

**Comment by Elforia** [comment]
What to know*

**Comment by Elforia** [comment]
OMFG

WANT to know**

**Comment by Elforia** [comment]
@Mackbit
I forgot to say that I am a druid.

**Comment by Mackbit** [comment]
Magic level trainer
----------------------
@Elforia 
If you want a really good (but expensive) magic level trainer (preferably used during double exp/skill weekends / with voucher), I could make a script that:

1) buys mana potions (either small/strong/great/ultimate depending on how much you want to waste)
2) use mana potions frequently + cast spells
3) sell flasks when potions are used
4) repeat to step 1)

This would be the fastest way of magic level training, but you will need to be rich to use it ;p.

About my scripts:
-------------------------------
I have plenty of small functions integrated in a large script. To mention some of the things I've made:

a) Shoot runes with mouse buttons (directly on crosshairs where the mouse pointer is)
b) Scroll through a set of runes (with HUD-overlay) so I can use one mouse button for multiple runes
c) Shoot waves/beams in the direction to the mouse pointer (much easier and faster to aim waves and it is actually possible to run with full speed in one direction, shoot one wave backwards and continue running as nothing had happened ^^)
d) HUD overlay + sound trigger for hp and mana (I don't have to look at my hp/mana, I will hear a sound when I should heal or refill mana, quite relaxing to hunt). Also added an overlay for my friends hp as I am a druid, so it's easier to keep track on his hp.
e) Multiple hotkeys on the same hotkey (I have for instance strong ice spike on the same hotkey as ice strike, the script has set the highest priority to the strongest spell, mening that it will always try to cast the strongest spell when it's ready (when cool-down is reset). Quite nice to have less hotkeys.
f) Utamo vita countdown HUD (I don't have to keep track of the time in my head, the script will alarm me when mana shield is near to run out)
g) Soft boots timer HUD overlay (keeps track on how much time is left on my soft boots). It's not perfect right now, the time offsets a bit but I am working on it.
h) Rashid city HUD overlay (tells me in which city Rashid is today)
i) Wild growth rune maker (I use it after every hunt to train magic level)

Here is a print-screen of how the HUD-overlays are integrated:
![alt tag](http://i.imgur.com/0ap81xz.png)

Comments
----------------------
You can go pretty far with AHK. Just keep in mind that I do not read any of Tibia's memory as bot-software do, so I can't make advanced things such as following waypoints from the map, killing creatures (hunting), etc, but that is never something I wanted to achieve since it would make the game boring. 

If you come up with any new, cool ideas, please let me know.

**Comment by Elforia** [comment]
@Mackbit
It sounds great to me! I am not rich yet, but I have some money that I want to spend training ML. I will be very thankful if you can make that script to me. =D

About this large script. May you share this one with me? I have no Idea how you get so far using this simple tool called autohotkey. You're amazing! A HUD to help me with my friends HP will help too much. Too much!

**Comment by Elforia** [comment]
@Mackbit 
What about a countdown to the Wild Growths? Is it possible?

**Comment by Mackbit** [comment]
@Elforia Alrighty! I will write a magic level trainer for you (I can probably finish it this week) that will have the functionality that I wrote earlier. 

About my large script: It is hardcoded for my screen display (so screen coordinates might not work properly for other users). I can share the code with you if you are interested, but I would recommend you to write a completely new script and copy features you like, one at a time, to make sure everything works. If you are new to programming, I would gladly help you via Skype/ts and implement features that you are interested in.

Rune countdown
----------------
A wild growth/+magic wall counter would indeed be possible. My approach would be to set the rune to a certain hotkey, and when the hotkey is used, trigger a HUD countdown for that rune. It would also be possible to append/add multiple counters (a bit more tricky) if multiple wild growth/m-wall instances are used at the same time. I like the idea of this feature and will add it to my main script.

**Comment by Elforia** [comment]
@Mackbit 
Wow! Thanks a lot, friend. I appreciate your goodwill!

### ML Trainer
Are you already thinking about a faster (Great Mana Potions) and slower (Mana Potions) way of training? As you said, I need to be rich (to use bigger potions) and I'm not... yet! Sadly.

### Rune countdown
Perfect! That's exactly what I had in mind when I suggest it. 👍 

### Large Script
The HUD can't be dragged though the screen? Changing position of them in the script can't be so hard. Right? xD

### One last thing
Where are you from?

**Comment by Mackbit** [comment]
@Elforia 

ML Trainer
------------------
I will implement the possibility for the user to initially choose one type of mana potion (small/strong/great/ultimate), and depending on what option that is made, set up a loop that will spend mana with spells according to the ingoing amount of mana from the different types of potions. The script will with other words have four different modes for the four different potion types. The fastest way of magic level training will then be using ultimate mana potions, but also the most expensive one. The user will be able to chose method depending on his/her economy. 

Large Script
------
It is not the HUD elements that are the issue, it's the position of the player on the screen (for aiming waves/beams), the position of health/mana-bars and other elements that are used (since I am not using data from Tibia memory, only data from what is seen on the screen). Most of the functionality in my large script will likely work for you, but some functionality based on screen positioning of Tibia elements might not. I never implemented dynamic identification of Tibia elements since I implemented all code for my own use, but this might be of interest if other people wants to use my script. Some other issues are that all functionality is not easily understood by other users as it is right now and using the full script without modifications or knowledge might result in problems. My idea would be making a new project from scratch and make each feature of interest properly working for all types of users.

I am from Sweden :>

**Comment by Elforia** [comment]
## Large script
Oh! Ok, I understood. I'll need some help then.

I'm sure that if you make it functional for every other player, many people will use your script. My friends will!

**Comment by Elforia** [comment]
@Mackbit
## Large script
Oh! Ok, I understood. I'll need some help then.

I'm sure that if you make it functional for every other player, many people will use your script. My friends will!

**Comment by Elforia** [comment]
@Mackbit 
How can I see this large script? I am eager to test it.

**Comment by Mackbit** [comment]
@Elforia I will upload it later tonight.

**Comment by Elforia** [comment]
@Mackbit 
Thank you so much. I will test it right now and tell you later what works to me and what not. After a fast look I noticed that I need to change MANY things. (our hotkeys are completely different. So, I need to change each line that a hotkey appears)

Man! Thanks again, for being so polite and for your goodwill on helping me. 👍

**Comment by Mackbit** [comment]
@Elforia Yea, there are probably a lot of things you need to adjust before everything works properly.

I have now added a development page for your magic level trainer script. You can follow the progress at:
https://github.com/Mackbit/Tibia_ml_trainer

**Comment by Elforia** [comment]
@Mackbit do you have WhatsApp, Telegram, or something like that? I need help. haha

First of all I need to understand what F11, F7 and F8 means, to replace it with my respective keys.

**Comment by Mackbit** [comment]
@Elforia I have Skype and I am usually available after 19.00 CET, you can add me (search for mackiiboy), and we can talk tonight if you are available.

**Comment by Mackbit** [comment]
@Elforia Your magic level trainer is now finished. You can check it out at https://github.com/Mackbit/Tibia_ml_trainer
Would be cool if you could try the script and see if it is working.

**Comment by Elforia** [comment]
@Mackbit
# Damn!
You works fast, huh!? I tried it all, but it is not working well.

 It works better than "well". Buying, selling, casting spells... Everything works perfectly! You did a good choice when you put utana vid in your ML Trainer. Does not matter what kind of potion we use, utana vid works great! I used to train casting randomly spells, like tera hur, mas res... Not anymore. Thanks for showing me that! ;)

Thanks a lot. It is amazing!

## Large Script
Well... I am felling like I am Victor Frankenstein. I picked parts from everything you did and "write" my own script (deleting some parts and using others from my old script) It is terrible and looks like a monster. But it works!

Everytime that I tried to change a hotkey, to fit with my own hotkey set, an error appears. I spent some time on it, but I failed. So, I splitted every part of your large script and tested each of them separately.

I hadn't time to read script again, but I am sure that everything will works after some days. 

### Smart Exit
Very nice!


### Rashid + Utamo Vita display + Soft boots + Rune changer + Rune Lock GUI
It works, except on showing Soft Boots time. But it is my fault! I do not know how to show to this "guy" where the boots is.

### F7/F8/Cooldowns
Very useful

### ImgScan
I need a fast explanation about how it works. I'm sure that I can make it works if I have more details here. It is needed to the friends health HUD, right!?

### Utamo Vita
Just changed hk to F1.

###Strong and Weak wave
That one is the main reason that I spend some hours on your script

How hard was to discover that I needed a part of settings.ini to fix the wave script. HAHA! I was on my bed, preparing myself to sleep when I remembered that I saw something, somewhere, telling me values of xm and ym. (the values  to works here: xm = 380/ym = 300. Looking the old values I supposed that you have an full hd screen. Right?)

Now it works perfectly.


### Display runes
It do what it do.

### Send Rune
Why do I walk when I use it? Character go to the place where rune was thrown.

HUD of friends health
Can you give me a fast explanation about how to make it works here?

**Comment by Mackbit** [comment]
@Elforia 
# Magic level trainer
I am glad to hear that it works as this script was programmed to work for many different users. One thing that could be implemented in the future would either be a pause button or that it automatically pauses when the Tibia window is inactive, but I do not find it urgent to fix since the script is intended to be used for many hours. An other thing that could be implemented is an automatic detection of movement, i.e if someone tries to push your character away from the NPC, the program could either alarm you, try to walk back or logout.  That will be something to think about in the future.

## Large Script
Goo job! That is the best way of doing it, take one piece at a time and puzzle it all together to prevent errors. 

### Smart Exit
I like it too! It has saved me from deaths multiple times. When I get a long freeze, I'll use it and be back the next second.

### Soft boots timer
The soft boots functionality is based on following four parameters:

color_boots := 0xBDA2FF
color_worn_boots := 0x120B24
x_boots := 1807-2
y_boots := 325-3-12

You will have to change x and y_boots (the coordinates where the script are looking for the color of a certain pixel). It is really ugly programmed since if you are just one coordinate off, it will not work.  I will look into a better solution in the future. 

### F7/F8/Cooldowns
I don't know why it is not working for you. Try to look into the code and understand what it does. This code is not perfect since it assumes that you always succeed with sending the strong spell (which is not always the case). A better approach in the future will be using image search techniques that tries to find the image of the spell cool-down for verification. I will implement that in the future. 

### ImgScan
The ImgScan code is quite new, I programmed that one two weeks ago, so the code is really ugly and hardcoded. The things it do is searching for colors in the Tibia client (for instance color of your health bar, color of your mana bar, color of the boots that are being used and color of your friends HP. 

The color of your hp/mana-bar has the same color everywhere if you scan through the x-direction (-----> direction). If you take a printscreen and zoom in into the bar, you can see that. The thing I did was finding the x and y coordinates of each bar, and then check the color of the bars for different locations in the x-directions. With the information of the color, you will know how much % hp/mana you have since the color will either be red/blue or grey. This image illustrates the pixel search; at each white spot, I search for the color:

![alt tag](http://i.imgur.com/yd8A1xY.png)

When it comes to searching for your friends hp, I took a printscreen of the friends name in the battle log, cropped out that name, made all background black except the text and saved it as a .png-file. The script uses this image and tries to find a match on the screen. Look at the file sven.png in the folder and you will understand. 

###Strong and Weak wave
Yea, this is the main reason why my main script does not work properly for all users, it depends on your screen dimensions and how things are located in the Tibia client. Nice that you figured it out!

### Send Rune
Try to set the hotkey to "with crosshairs", that will probably solve it. If you look in the script, I am using a mouse click action, this action will make you walk if you are not using runes with crosshairs.

**Comment by Elforia** [comment]
@Mackbit 
### ImgScan

> color_hp := 0x6161F1 
color_mana := 0xFF7174
color_loot := 0x1F1F1F -- ??

These are the codes to the colours in pixels choose by me.
Is "loot" the space where we have no life/mana? If yes, the color shown to me is 0x5F605S

> x_green := 1185-1
x_lowgreen := 1160-1
x_yellow := 1150-1
x_red := 1125-1
y_hp := 156-8

What means that "-1" and "-8" after X and Y location?

![image](https://cloud.githubusercontent.com/assets/25248050/22743502/82a8d8ba-ee01-11e6-8574-7d0ecec8938a.png)

What am I doing wrong? Why 2 sven pics?

![image](https://cloud.githubusercontent.com/assets/25248050/22744733/5fadd276-ee05-11e6-8478-597c9231b7b1.png)

> while 1{
	; Search for Guide Behil's name from guide.png
	ImageSearch, FoundX, FoundY, 150, 30, A_ScreenWidth, A_ScreenHeight, *TransBlack guide.png

Do I need to change 150, 30 to?

**Comment by Mackbit** [comment]
@Elforia 

Do you remember the wild growth rune maker I made? This text here is the rune maker integrated into my main script. Instead of manually opening the wild growth rune maker after every hunt, I added a hotkey that automatically starts the script (by setting how many runes to make in a data file, that the rune maker reads). 
![image](https://cloud.githubusercontent.com/assets/25248050/22745668/801c19d4-ee08-11e6-8a1c-96c8cb7ca98a.png)
This data is simply (blank runes)-(mana potions)-(cap)-(soul points) in a string as you can see.

### ImgScan

color_loot := 0x1F1F1F -- ??

"Loot" is the color of the loot notification from TibiaLyzer (google TibiaLyzer if you don't know that it is). I added a feature that checks for loot notifications, and if a notification is found, it plays a sound notification. If you do not use TibiaLyzer, you can just remove the sound feature. 

##What means that "-1" and "-8" after X and Y location? 
> x_green := 1185-1
x_lowgreen := 1160-1
x_yellow := 1150-1
x_red := 1125-1
y_hp := 156-8

It is simple math, (subtraction). When I used this script for Tibia 10, the positioning of elements where a bit different, in fact, +1 in x and +8 in y direction. When I started to use Tibia 11 client, I manually adjusted the location, which is why you see this math.

##Why 2 sven pics?
One of them is a left over from a test I made. sven2.png is not used anymore and will be deleted. I made a change that made it possible to use transparent pictures (which is required to make it work). sven.png has a black background, as you can see. This black background is simply removed by  the *TransBlack argument in the ImageSearch function. 

##ImageSearch

ImageSearch, FoundX, FoundY, 150, 30, A_ScreenWidth, A_ScreenHeight, *TransBlack guide.png

This will search for guide.png on your screen and return FoundX and FoundY coordinates. These coordinates are not located on the NPC/players health bar, which is why I am adding an offset on the coordinates as:

xh := FoundX+3
yh := FoundY+15

These coordinates is located on the health bar in the battle list, and from these coordinates it's possible to fetch the color of the bar. (You can make it even more advanced and try to fetch multiple coordinates in order to calculate % hp)

**Comment by Elforia** [comment]
@Mackbit 
### Runes
It is really cool. But it do not show right values of my cap and soul. But I do not care at all and I will not try to fix it. I can just run it and put values at the window, as I am doing until now, since I found your runemaker script.

### Tibialyzer
I know it. https://github.com/Mytherin/Tibialyzer/issues/259
That is how I found you. ^^

### Coordinates
I got the idea, but did not got how to make it works. But forget it! Tibia 11 already give me HUDs to my own hp and mana. I was only looking for a way to show me a hud for friends hp. And...

Finally it works!!
![image](https://cloud.githubusercontent.com/assets/25248050/22787955/3daf545e-eec5-11e6-89e4-6d7a9bceb439.png)


> You can make it even more advanced and try to fetch multiple coordinates in order to calculate % hp

I do not know how to do it. I am completely new at programming and I am learning too much with you. But, maybe, if you show me how to make it... 

### F7 / F8

Is that wright? I've always asking myself what do you use on F8 and ^F11.
> $F5::

> if (busy_cooldown = 0 && busy_special = 0){
	busy_cooldown = 1
	SetTimer, RestoreCooldown, 2050
	if (busy_gran = 0){
		Send +{F5} ---------------------------------- exori gran frigo
		busy_gran := 1
		SetTimer, RestoreGran, 8000
	}
}
else{
	Send {F5} ----------------------------------------- exori frigo
}
return

### Wild Growth countdown
Do not forget to tell me if someday you write a script to show it. 👍

**Comment by Elforia** [comment]
´]ç]j~ç

**Comment by Elforia** [comment]
@Mackbit 

Thanks for helping me, bro. I think that I take too much of your time. Sorry. ^^

**Comment by Mackbit** [comment]
@Elforia 
### Runes
The reason it does not show the right values of your cap/soul is because I never implemented that feature. I simply added a hotkey on PgDn and Ctrl+PgDn that changes the displayed values and input to the rune maker. If you want to implement detection of cap/soul points, you would need to save 10 number image files (0-9) and detect text on the area of interest on your screen. The tricky part is that you will either find 1, 2 or 3 numbers of soul points (1 number is 0-9, 2 numbers is 10-99 and 3 numbers is 100-200), same goes for cap but there you could find even more numbers, i think up to 5(?), which makes it a bit more advanced.  

### Coordinates
"You can make it even more advanced and try to fetch multiple coordinates in order to calculate % hp". If you want to implement this, you will have to find the first x coordinate (the first to the left) of the health bar in the battle list, and then check the color of the next x-coordinate .... until the last x-coordinate of the health bar. If the health bar is 200px wide, it would mean 200 color checkups. With this information, you will know coordinates that have gray color and which coordinates that have other color (green/yellow/red etc). If 20 coordinate values are gray, you know that 20/200 = 10% of your friends hp is gone, i.e your friend has 90% hp left. 

How to implement this? Below I've written a simple pseudo-code that would work:

1. Find the first x-coordinate of the health bar, lets name it to x_init. (You will also need y_init, the height where the health bar is located)
2. Create a for-loop, xi for xi in range(x_init to x_init + length of health bar) with a counter that increments its index after each loop (lets call this variable counter) and check the color at coordinate xi, y_init. 
3. If color == gray, break the loop and return the value of the counter (the index).
4. Then you can calculate the % hp = counter/length of heath bar.

### F7 / F8
Do you have the RestoreCooldown and RestoreGran methods in your script? The timers runs these methods after 2 and 8 seconds as you can see in the script. The methods will set a cooldown state to either 0 or 1, where 0 == not busy and 1 == busy, where busy means that the strong spell not will be applied.

### Wild Growth countdown
I will update you when I implement this feature in the future. The feature itself is not hard to implement, but I am not yet sure how to implement multiple timers at the same way in an easy way. I will probably figure something out.
